import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen"}>
        <div className="flex flex-col min-h-screen">
          {/* NAVBAR */}
          <nav className="w-full flex items-center justify-center py-3 bg-blue-400">
            NAVBAR
          </nav>
          <main className="container mx-auto py-16 px-10 flex-grow bg-red-500">
            {children}
          </main>
          {/* FOOTER */}
          <footer className="w-full flex items-center justify-center py-3 bg-yellow-400">
            FOOTER
          </footer>
        </div>
      </body>
    </html>
  )
}
